# Generated by Django 6.0.2 on 2026-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='encrypted_file_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
