# Generated by Django 6.0.2 on 2026-02-24 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_securefile_encrypted_file_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiry_time', models.DateTimeField()),
                ('max_downloads', models.IntegerField(default=1)),
                ('current_downloads', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.securefile')),
            ],
        ),
    ]
